### PR TITLE
Switch to Quarkus as runtime #359

### PR DESCRIPTION
**Pull request by lburgazzoli**
**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by nicolaferraro** [comment]
I got something wrong in the catalog:

```
    camel-k-cron:
      groupId: org.apache.camel.k
      artifactId: camel-k-cron
      schemes:
      - id: cron
        http: true
        passive: false
    camel-k-kamelet:
      groupId: org.apache.camel.k
      artifactId: camel-k-kamelet
      schemes:
      - id: kamelet
        http: false
        passive: true
```

Cron is not http, while kamelet is not necessarily passive (most of the times it's active actually).
We've already had a discussion about kamelets but I don't remember what was the right way to set it... I mean there's no good way probably, but how we deal with them?

**Comment by nicolaferraro** [comment]
> I got something wrong in the catalog:
> 
> ```
>     camel-k-cron:
>       groupId: org.apache.camel.k
>       artifactId: camel-k-cron
>       schemes:
>       - id: cron
>         http: true
>         passive: false
>     camel-k-kamelet:
>       groupId: org.apache.camel.k
>       artifactId: camel-k-kamelet
>       schemes:
>       - id: kamelet
>         http: false
>         passive: true
> ```
> 
> Cron is not http, while kamelet is not necessarily passive (most of the times it's active actually).
> We've already had a discussion about kamelets but I don't remember what was the right way to set it... I mean there's no good way probably, but how we deal with them?

Ok, kamelet should be right, because the template is added as additional source and analyzed.

**Comment by nicolaferraro** [comment]
Is this right? https://github.com/apache/camel-k-runtime/blob/00d401e5e875d0e4d186edc4f00266f64bb68ed3/support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3x.java#L148

**Comment by lburgazzoli** [comment]
> Is this right?
> 
> https://github.com/apache/camel-k-runtime/blob/00d401e5e875d0e4d186edc4f00266f64bb68ed3/support/camel-k-maven-plugin/src/main/java/org/apache/camel/k/tooling/maven/processors/CatalogProcessor3x.java#L148

no

**Review by nicolaferraro — APPROVED** [review]

**Pull request merged**
