### PR TITLE
Upgrade to camel-quarkus 1.8.0, camel 3.9.0

### LINKED ISSUE #626: PR actions failing
PRs are failing because `No such image: testcontainers/ryuk:0.3.0`. It seems related to this [issue](https://github.com/testcontainers/testcontainers-java/issues/3574).

This should be fixed by using testcontainers version `1.15.1` instead of `1.15.0`. Dependency is updated in camel `3.8.0` but not in `3.7.0`, so likely we should have this fixed when bumping the camel version.

### PR DESCRIPTION
**Pull request by lburgazzoli**
Fixes #626

**Release Note**
```release-note
The camel-k-loader-* have been replaced by the respective artifacts from
camel-quarkus
The camel-k-loader-jsh has not been migratined as it requires Java > 9
and Camel is still supporting Java 8
The camel-k-loader-yaml is provided by camel-k to workaround CAMEL-16424
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by lburgazzoli** [comment]
@nicolaferraro mind testing it against the latest camel-k ?

**Comment by nicolaferraro** [comment]
The "hello worlds" seem to work in all langs except groovy:

```
2021-03-29 15:24:02,979 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.IllegalArgumentException: org.apache.camel.util.function.ThrowingBiConsumer referenced from a method is not visible from class loader
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.ensureVisible(Proxy.java:858)
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.validateProxyInterfaces(Proxy.java:681)
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:627)
        at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:635)
        at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$0(Proxy.java:415)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
        at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
        at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:413)
        at java.base/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1006)
        at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:318)
        at org.apache.camel.dsl.groovy.GroovyRoutesBuilderLoader.loadRoutesBuilder(GroovyRoutesBuilderLoader.groovy:63)
        at org.apache.camel.impl.engine.DefaultRoutesLoader.findRoutesBuilders(DefaultRoutesLoader.java:100)
        at org.apache.camel.spi.RoutesLoader.findRoutesBuilders(RoutesLoader.java:66)
        at org.apache.camel.k.support.SourcesSupport.load(SourcesSupport.java:104)
        at org.apache.camel.k.support.SourcesSupport.loadSources(SourcesSupport.java:75)
        at org.apache.camel.k.listener.SourcesConfigurer.accept(SourcesConfigurer.java:57)
        at org.apache.camel.k.listener.AbstractPhaseListener.accept(AbstractPhaseListener.java:32)
        at org.apache.camel.k.quarkus.Application$ListenerAdapter.invokeListeners(Application.java:135)
        at org.apache.camel.k.quarkus.Application$ListenerAdapter.beforeConfigure(Application.java:97)
        at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:533)
        at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:116)
        at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:86)
        at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
        at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:137)
        at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
        at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy_0(CamelBootstrapProcessor$boot-173480958.zig:101)
        at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot-173480958.deploy(CamelBootstrapProcessor$boot-173480958.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:523)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)
```

**Comment by lburgazzoli** [comment]
@nicolaferraro can you try again with the latest code ?

**Comment by lburgazzoli** [comment]
@nicolaferraro ping

**Comment by nicolaferraro** [comment]
> @nicolaferraro ping

Checking...

**Comment by nicolaferraro** [comment]
Same issue with groovy, also updating camel-quarkus to 1.8.1

**Review by nicolaferraro — APPROVED** [review]

**Pull request merged**
