### PR TITLE
knative eventing

### PR DESCRIPTION
**Pull request by akihikokuroda**
This commit adds the component that handles the Knative eventing GitHub source.
It supports create, get, list and delete for the GitHubSource.sources.knative.dev/v1alpha1 CRD instance.
It also supports notifications for the instance changes.

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by lburgazzoli — CHANGES_REQUESTED** [review]
@akihikokuroda thx for the PR but there's a few things that nee to be addressed:
1. component should be contributed to apache/camel when possible, component listed here are gogin o be moved there as soon as possible
2. Wonder that we could probably achieve what this component does by implementing https://issues.apache.org/jira/browse/CAMEL-14003 os then we can support any CR instead just the github source one

**Comment by akihikokuroda** [comment]
@lburgazzoli Thank for looking at this.  What can be done next?   May I move this to Camel and deprecate when CAMEL-14003 is implemented?  Should I wait for CAMEL-14003 or implement it?  What is your suggesting?  Thank!

**Comment by lburgazzoli** [comment]
@akihikokuroda my preferred option would be to have CAMEL-14003 done so if you have any time to contribute to that, it would be very appreciated

**Comment by akihikokuroda** [comment]
OK.  I'll try that.  I probably need help with its interface design.

**Comment by lburgazzoli** [comment]
> OK. I'll try that. I probably need help with its interface design.

sure

**Pull request closed without merging**
