### PR TITLE
Rebase camel-main on main

### PR DESCRIPTION
**Pull request by orpiske**
**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Comment by orpiske** [comment]
This is not right. I'll fix it.

**Review by oscerd — APPROVED** [review]
I don't know if it's better to avoid backporintg changelog updates. We can backport just all the other commits, once we merge camel-main on main, the first time the changelog action will run we'll have the changelog updated

**Comment by orpiske** [comment]
> I don't know if it's better to avoid backporintg changelog updates. We can backport just all the other commits, once we merge camel-main on main, the first time the changelog action will run we'll have the changelog updated

Yeah!  I'm wondering what might make it easier later on, when we have to merge `camel-main` on `main`. Do you have any preference / opinion?

**Comment by orpiske** [comment]
> This is not right. I'll fix it.

Doing it the other way around seems to make it right and avoid the changelog conflict.

**Comment by oscerd** [comment]
I think i would probably focus all the non changelog related commit. In the end the changelog can be run separately in a second time.

**Comment by oscerd** [comment]
Ah now, I get your point, yeah, using the other way around should work.

**Comment by orpiske** [comment]
BTW, the Camel K one has some code conflicts. So I am not sure if I'll manage to finish that one today ... but it's in progress.

**Pull request merged**
