### PR TITLE
GroovyDSL was moved to another package in Camel 3.10

### PR DESCRIPTION
**Pull request by orpiske**
**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by lburgazzoli** [comment]
this adhoc camel-k-groovy/* artifacts can probably be removed

**Comment by orpiske** [comment]
> this adhoc camel-k-groovy/* artifacts can probably be removed (keep the test if any)

Done, thanks! I may have been a bit conservative as I left the `GroovySourceLoaderFeature`. 

wdyt?

**Comment by lburgazzoli** [comment]
feel free to drop it :)
it has been added to workaround an issue but does not make any sense to keep it here

**Comment by orpiske** [comment]
> feel free to drop it :)
> it has been added to workaround an issue but does not make any sense to keep it here

Thanks for reviewing it! I'll nuke the whole `camel-k-loader-groovy`, in this case.

**Pull request merged**
