### PR TITLE
feat(catalog) : Add telemetry capability

### PR DESCRIPTION
**Pull request by gansheer**
Uses camel-quarkus opentelemetry extension for new telemetry capability in catalog

resolves #apache/camel-k#3519

**Release Note**
```release-note
feat(catalog): Add telemetry capability
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by tadayosi — APPROVED** [review]

**Comment by squakez** [comment]
I think it's good to go. @gansheer can I merge this one?

**Comment by gansheer** [comment]
> I think it's good to go. @gansheer can I merge this one?

Please do, it will help me write the e2e test for the camel-k PR. 

I was waiting for some first review on the camel-k PR, but you are all so fast to review :scream:  (that's awesome).

**Comment by squakez** [comment]
> > I think it's good to go. @gansheer can I merge this one?
> 
> Please do, it will help me write the e2e test for the camel-k PR.
> 
> I was waiting for some first review on the camel-k PR, but you are all so fast to review scream (that's awesome).

You'll be soon wondering if @oscerd is a bot [1]... :P

https://syndesis.io/faq/#is-oscerd-a-bot

**Comment by gansheer** [comment]
> 
> You'll be soon wondering if @oscerd is a bot [1]... :P
> 
> https://syndesis.io/faq/#is-oscerd-a-bot

I already decided that he has a superpower :superhero_man:

**Pull request merged**
