### PR TITLE
fix(core): Error handler regression

### PR DESCRIPTION
**Pull request by squakez**
Workaround reintroduced to fix a Camel regression as specified in https://github.com/apache/camel-k/issues/3560#issuecomment-1230042204

Ref #3560

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Comment by squakez** [comment]
FYI @oscerd . We'll need a new staging for 1.14 expected by Camel K 1.10. I've noticed we've already bumped to 1.14.1 in `main`, not sure if this affects Camel K as well.

**Review by tadayosi — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
I'll delete tag and get back to 1.14.0 don't worry

**Comment by tadayosi** [comment]
@squakez @oscerd Btw Camel Quarkus 1.12.0 is about to be released. Does it make sense to upgrade to 1.12.0 for Camel K runtime 1.14.0 as well?

**Comment by squakez** [comment]
> @squakez @oscerd Btw Camel Quarkus 1.12.0 is about to be released. Does it make sense to upgrade to 1.12.0 for Camel K runtime 1.14.0 as well?

Is there any important feature/fix that we need in Camel K? if not I'd keep this and wait for next version to upgrade that dependency as well.

**Comment by oscerd** [comment]
To me it's better to release as is and immediately release a new camel k with 2.12.0 quarkus. We need to give something to the community. it's too much time we are not releasing

**Pull request merged**
