### PR TITLE
fix(examples) - update path to runner.jar

### PR DESCRIPTION
**Pull request by tplevko**
The issue with the examples was caused by change in the structure of built quarkus projects after the upgrade for more info about the issue see: https://github.com/apache/camel-k-runtime/issues/641

**Release Note**
```release-note
fix(examples) - update path to runner.jar
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by lburgazzoli** [comment]
@tplevko the quarkus team has added support for system properties and env vars [1][2] to the quarkus:dev mojo, wonder if the examples should leverage quarkus:dev to run the examples and support running them in jvm mode only

[1] https://github.com/quarkusio/quarkus/issues/14401
[2] https://github.com/quarkusio/quarkus/pull/14523

**Comment by tplevko** [comment]
@lburgazzoli what you are proposing sounds great. One thing that however that crossed my mind is if this wouldn't hide the key features of the runtime for a newcomer to this runtime (e.g. someone like me). Couldn't it be added as one of the options how to run the examples, leaving the native mode as it is now?

Anyway, I am not sure this is something I am too knowledgeable about, these are just my observations. I was in this PR just trying to get the examples to work.

Also I would like to ask, whether there is some issue with the checks, or I should investigate what might have caused the failures. I'm not really aware what might have caused the failures in the automation.

**Comment by lburgazzoli** [comment]
> @lburgazzoli what you are proposing sounds great. One thing that however that crossed my mind is if this wouldn't hide the key features of the runtime for a newcomer to this runtime (e.g. someone like me). Couldn't it be added as one of the options how to run the examples, leaving the native mode as it is now?
> 

I think we can keep the native build, may require a little bit more work but yes, it should be possible.

> Anyway, I am not sure this is something I am too knowledgeable about, these are just my observations. I was in this PR just trying to get the examples to work.
> 

I'll try to do it once this get merged, unless you want to try to do it yourself.

> Also I would like to ask, whether there is some issue with the checks, or I should investigate what might have caused the failures. I'm not really aware what might have caused the failures in the automation.

Restarted the job

**Comment by tplevko** [comment]
Thanks for the rerun, it seems like it helped.

> I'll try to do it once this get merged, unless you want to try to do it yourself.

Sounds great, I can definitely try to do it!

**Comment by lburgazzoli** [comment]
@tplevko thx for fixing this, if you need any support, ping me

**Pull request merged**
