### PR TITLE
Suport for camel 3.0.0-M2 and 2.21.x

### PR DESCRIPTION
**Pull request by lburgazzoli**
this supersede #39

I think we should discuss the option to drop support to camel 2.x when 3.x will hit its first release but till that date we should make some effort to support both.

@davsclaus @nicolaferraro @oscerd @astefanutti, what do you think ?

### CODE REVIEW

**Comment by davsclaus** [comment]
Yeah I think Camel 2.x is to be considered deprecated and when Camel 3 is GA then Camel K 1.0 GA only supports Camel 3 onwards. And if it gets to complex to have 2.x and 3.x at the same time then we should drop 2.x in favour of 3

**Comment by oscerd** [comment]
Just a doubt about the camel 2.21.x version. Is it better to point to the last 2.21 released version?

**Comment by lburgazzoli** [comment]
> Just a doubt about the camel 2.21.x version. Is it better to point to the last 2.21 released version?

It should not matter as the goal is to test compatibility with 2.21.x so any release should be fine but I can update it.

**Comment by oscerd** [comment]
> > Just a doubt about the camel 2.21.x version. Is it better to point to the last 2.21 released version?
> 
> It should not matter as the goal is to test compatibility with 2.21.x so any release should be fine but I can update it.

Ok then. Leave it as is.

**Pull request merged**
