### PR TITLE
Support endpoint DSL in YAML/JSON

### LINKED ISSUE #366: Support endpoint DSL in YAML/JSON
Instead of:

```
route:
  from:
    uri: telegram/bots?chatId=1234
  steps:
  - to:
      uri: knative:endpoint/sink
```

We may have (alternative):

```
route:
  from:
    telegram:
      type: bots
      chatId: 1234
  steps:
  - knative:
      type: endpoint
      name: sink
```

It's not only syntactic sugar, the most important part of the syntax below is that it's possible to define the **full json/yaml schema** of the endpoints, so that a web console or IDE can automatically suggest components and their properties and also completely validate the DSL.

There are tools for IDE that support URI validation, but they need a language server. This would be LSP free.

Maybe we can start moving the DSL to apache camel in order simplify impl.

### PR DESCRIPTION
**Pull request by lburgazzoli**
Fixes #366

**Release Note**
```release-note
The YAML DSL now supports to use an endpoint-dsl alike structure, like:

- route:
    from:
      direct:
        name: "endpoint"
        timeout: "#property:direct.timeout"
    steps:
      - telegram:
          type: "bots"
          authorization-token: "#property:telegram.token"
      - mock:
          name: "telegram"
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]
Oh this is really nice. Going to make that even easier.

Whoa the schema is 40000 lines - glad its auto generated ;)

**Comment by lburgazzoli** [comment]
@davsclaus the main issue about this implementation is that it requires the camel catalog to look up the Json and construct the URI, wonder if we can use something similar to the component customizer where the catalog searches for some "factory" that provides an auto generated code to construct the endpoint URI from a map of properties and if does not find it, it fall-back to the original mechanic.

**Comment by davsclaus** [comment]
Yeah that is a good idea. I created a ticket
https://issues.apache.org/jira/browse/CAMEL-15567

**Comment by davsclaus** [comment]
We can actually also use this in the http components where we do some endpoint uri rebulding, that could benefit from this.

**Pull request merged**
