### PR TITLE
Use camel-dependencies instead of our own

### LINKED ISSUE #459: Use camel-dependencies instead of our own
For dependencies then shouldn't we try to align this with camel-core better, and use camel-dependencies instead of having many of our own defined in the root pom.

### PR DESCRIPTION
**Pull request by lburgazzoli**
Fixes #459

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
There is 3.4.3 out, but I guess you just want to wait for 3.5.0

**Comment by lburgazzoli** [comment]
> There is 3.4.3 out, but I guess you just want to wait for 3.5.0

yes

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
Ah nice so its a dot vs dash war ;)

**Comment by lburgazzoli** [comment]
> Ah nice so its a dot vs dash war ;)

Was tempted to keep it mixed :P

**Pull request merged**
