### PR TITLE
Prepare release 1.17.0

### LINKED ISSUE #950: Upgrade for Camel 3.20.1
Upgrade to Camel 3.20.1 and Camel-quarkus 2.16.0

### PR DESCRIPTION
**Pull request by oscerd**
**Release Note**
```release-note
Upgrade to Camel 3.20.1, Quarkus 2.16.0.Final and Camel-Quarkus 2.16.0
```

Fixes #950 and related to #951 

Still waiting for Quarkus platform 2.16.0.Final release.

### CODE REVIEW

**Comment by oscerd** [comment]
Seems we have this problem with Kube client.

`Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.fabric8.kubernetes.client.ConfigBuilder.getFile(). This error is reported at image build time because class io.fabric8.kubernetes.client.ConfigFluentImplConfigurer is registered for linking at image build time by command line`

**Comment by oscerd** [comment]
And we have always the problem of Mandrel not update to 22.3.0

**Comment by squakez** [comment]
About Mandrel distro, is it that we don't want to use because we only have JDK 17 supported at this stage?

**Comment by oscerd** [comment]
> About Mandrel distro, is it that we don't want to use because we only have JDK 17 supported at this stage?

Yes

**Pull request merged**
