### PR TITLE
Fixes #556, Renamed wrap component to kamelet-reify

### LINKED ISSUE #556: Rename wrap component to kamelet-reify

### PR DESCRIPTION
**Pull request by dhirajsb**
**Release Note**
```release-note
Renamed wrap component to kamelet-reify
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by lburgazzoli** [comment]
@dhirajsb wonder if having `kamelet` as part of the component name could be misleading (yes I know, `wrap` is also misleading) as it is true that at the moment the main use case is for kamelts but it is not limited to that context.

**Comment by dhirajsb** [comment]
@lburgazzoli I did ask for feedback on the name. But, Claus was the only one who responded with a +1, so here we are. :smile: 

I agree that in principle, the wrap mechanism works in non-kamelet contexts too. Do you foresee it being used for anything else in let's say the next year or two? Even if it is, there is no harm in carrying along the kamelet prefix, sort of an origin story of where this component came from. WDYT?

**Comment by dhirajsb** [comment]
Also created https://github.com/openshift-integration/kamelet-catalog/pull/9 to use the new scheme name.

**Comment by lburgazzoli** [comment]
> @lburgazzoli I did ask for feedback on the name. But, Claus was the only one who responded with a +1, so here we are. smile
> 

Oh, I've missed it 

> I agree that in principle, the wrap mechanism works in non-kamelet contexts too. Do you foresee it being used for anything else in let's say the next year or two? Even if it is, there is no harm in carrying along the kamelet prefix, sort of an origin story of where this component came from. WDYT?

I do agree, there's no harm in renaming it as you proposed but to avoid a second rename, let just take one or more days and see if we can find a better name, if not, let's go with `kamelet-reify` :)

**Comment by dhirajsb** [comment]
@lburgazzoli were you able to think of something more specific but still generic enough for this component? An alternative I can come up with is delegate, since the component does just that. But it's not any better than wrap to be honest. That's why I originally thought it was better to name it something specific to the immediate purpose it's built to satisfy.

**Comment by lburgazzoli** [comment]
No, I honestly had no time so I'm ok with this

@nicolaferraro @davsclaus what do you think ?

**Comment by davsclaus** [comment]
LGTM

**Review by nicolaferraro — APPROVED** [review]

**Pull request merged**
