### PR TITLE
Fix #170: add support for webhook endpoints

### LINKED ISSUE #170: Add support for webhook endpoints
I'm working on adding support for Camel 3 "webhook:" prefixed endpoints.

### PR DESCRIPTION
**Pull request by nicolaferraro**
Fix #170

When `CAMEL_K_WEBHOOK_ACTION` is set to `REGISTER` or `UNREGISTER`, the webhook route policy executes the registration/deregistration of all webhooks appearing on the routes and terminates the camel context without starting the routes.

This will be used in combination with a new workflow to be implemented in Camel K.

### CODE REVIEW

**Comment by lburgazzoli** [comment]
Maybe this should be a customizer ?

**Comment by nicolaferraro** [comment]
> Maybe this should be a customizer ? and maybe in its own artifact

Not sure.. let me think about it..

If the behavior can be activated only by a trait (and I think it's acceptable), yeah, it's possible to externalize it in a lib with a customizer

**Comment by lburgazzoli** [comment]
> > Maybe this should be a customizer ? and maybe in its own artifact
> 
> Not sure.. let me think about it..
> 
> If the behavior can be activated only by a trait (and I think it's acceptable), yeah, it's possible to externalize it in a lib with a customizer

That would be very good for quarkus pov

**Comment by lburgazzoli** [comment]
Minor thing, add the artifact to the bom and to the registry

**Pull request merged**
