### PR TITLE
Prepare for 1.15.0 release: Align to Camel 3.18.1, quarkus 2.12.0.Fin…

### PR DESCRIPTION
**Pull request by oscerd**
…al and camel-quarkus 2.12.0

**Release Note**
```release-note
NONE
```

### CODE REVIEW

**Comment by squakez** [comment]
Maybe we should change `quay.io/quarkus/ubi-quarkus-native-image:22.1.0-java11` as well?

**Comment by oscerd** [comment]
I think so

**Review by squakez — APPROVED** [review]

**Comment by oscerd** [comment]
More errors are related to vertx method close from vertx-web.

**Comment by oscerd** [comment]
Not sure how it worths the effort to update to 3.18.1, while 3.18.2 is on vote.

**Comment by oscerd** [comment]
In 3.18.2 the vertx-web-client dependency is correctly aligned to vertx version 4.3.3. We should probably wait for it.

**Pull request closed without merging**
